n1 = int(input('Digite a primeira nota:\n'))
n2 = int(input('Digite a segunda nota:\n'))
n3 = int(input('Digite a terceira nota:\n'))
n4 = int(input('Digite a quarta nota:\n'))
print('A média de suas notas bimestrais é {}'.format((n1+n2+n3+n4)/4))