h = int(input('Quantas horas trabalhou esse mês?\n'))
sh = int(input('Quanto é a sua hora trabalhada?\n'))
salario = h*sh
if salario <= 900:
    print('Salário Bruto:{}'.format(salario))
    print('Imposto de Renda: Isento')
    print('INSS:{}'.format(salario*0.10))
    print('FGTS:{}'.format(salario*0.11))
    d = (salario*0.10)
    print('Total de Descontos:{}'.format(d))
    print('Salário Liquido:{}'.format(salario-(salario*0.10)))
elif salario > 900 and salario <= 1500:
    print('Salário Bruto:{}'.format(salario))
    print('Imposto de Renda:{}'.format(salario-(salario*0.95)))
    print('INSS:{}'.format(salario-(salario*0.90)))
    print('FGTS:{}'.format(salario-(salario*0.89)))
    d2 = (salario-(salario*0.90))+(salario*0.05)
    print('Total de Descontos:{}'.format(d2))
    tt = salario-((salario*0.05)+(salario*0.10))
    print('Salário Liquido:{}'.format(tt))
elif salario > 1500 and salario <= 2500:
    print('Salario Bruto:{}'.format(salario))
    print('Imposto de Renda:{}'.format(salario*0.10))
    print('INSS:{}'.format(salario*0.10))
    print('FGTS:{}'.format(salario*0.11))
    d3 = ((salario*0.10)+(salario*0.10))
    print('Total de Descontos:{}'.format(d3))
    tt2 = salario-((salario*0.10)+(salario*0.10))
    print('Salário Liquido:{}'.format(tt2))
elif salario > 2500:
    print('Salario Bruto:{}'.format(salario))
    print('Imposto de Renda:{}'.format(salario*0.20))
    print('INSS:{}'.format(salario*0.10))
    print('FGTS:{}'.format(salario*0.11))
    d4 = ((salario*0.20)+(salario*0.10))
    print('Total de Descontos:{}'.format(d4))
    tt3 = salario-((salario*0.20)+(salario*0.10))
    print('Salário Liquido:{}'.format(tt3))
else:
    print('Você digitou alguma informação inválida!!')
